name: loading_plus
description: This package is to help you with add loadings to your app in simple way.
version: 1.3.0
homepage: https://github.com/OsamaAssaf/loading_plus.git

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: